app/javascript/components/verifiable.html, app/javascript/components/verifiable.js
=> Hook up the 'No evidence' button

app/controllers/media_wiki_api_controller.rb, app/javascript/wikiapi.js
Having to rename action parameter as this clashes with Rails' action parameter
Closes #38
=> Fix API proxy after changes made for the real API

app/javascript/wikiapi.js
Property created here: https://test.wikidata.org/wiki/Property:P70901
=> Add parliamentary term properties for test API

app/javascript/components/verifiable.html, app/javascript/components/verifiable.js, package.json, yarn.lock
Closes #8 
Set Levenshtein distance between names to 5 which seems to work quite well.
New name submitted to the verification backend action but not used yet.
=> Frontend work for allowing name changes

app/javascript/app.html, app/javascript/app.js
- Move UI navigation components to the top
- Added statement type filter
- Switch to using vue watchers and computed values to make JS simpler
- Add transaction ID for debugging issues as using the statement index isn't going to work well with the type filter
=> Frontend improvements

app/javascript/wikiapi.js
=> Fix reconciliation search where there are no results from Wikipedia

app/javascript/app.css.scss, app/javascript/app.html, app/javascript/app.js
Fixes #78.
Also does a bit towards #76, but doesn’t fix it.
Builds on top of #83.
=> Styling for "Loading…" spinner

app/javascript/app.css.scss, app/javascript/app.html
=> More useful “no statements” message

app/decorators/statement_decorator.rb, app/services/retrieve_position_data.rb, spec/decorators/statement_decorator_spec.rb, spec/services/statement_classifier_spec.rb
Small refactors before making some changes to this query.
- Renaming fields to make more sense
- Line length and makes it easier to comment out which fields are being selected when debugging
- Be consistence how we're entering external values.
=> Refactor position data query

app/controllers/media_wiki_api_controller.rb, app/javascript/wikiapi.js, app/services/retrieve_position_data.rb
Closes #216 
This shows the name of the tool and links back to the page which the user was on when the change was made.
=> [#216] Add summary to all write Wiki API requests

app/models/page.rb
Fixes #231
Destroy statements associated to the page to prevent foreign key
constraint error.
=> [#231] Fix page deletion error

app/models/page.rb, db/migrate/20180704093403_remove_default_from_pages_csv_source_url.rb, db/schema.rb, spec/factories/pages.rb, spec/models/page_spec.rb
=> Make Page#csv_source_url required

app/javascript/app.js, package.json, yarn.lock
Fixes #218 
Table is now sorted by last name. Benchmarking the sorting it seems fast even tho its all done on the frontend with JS.
=> [#218] Sort statements by the person's last name

app/javascript/wikiapi.js
The two searches are completely independent, and we’re already inside a Promise, so it’s super easy to run the searches in parallel, rather than series, and then resolve the Promise once they’re both complete.
This saves time. In my development environment, "searching" went down from ~5 seconds to ~3 seconds.
It was also a good opportunity to break up the monolithic search method in wikiapi.js. Hopefully now it’s a bit easier to follow.
=> Reconciliation searches Wikidata and Wikipedia in parallel

app/javascript/app.html, app/javascript/components/action_wrapper.html, app/javascript/components/action_wrapper.js, app/javascript/components/actionable.html, app/javascript/components/actionable.js, app/javascript/components/loading.html, app/javascript/components/loading.js, app/javascript/components/reconcilable.html, app/javascript/components/reconcilable.js, app/javascript/wikiapi.js
Fixes #172 
Improves the loading messages and shows what is happening:
=> [#172] Better loading messages

app/javascript/app.css.scss, app/javascript/app.html, app/javascript/components/statement.html, app/javascript/components/statement.js, app/services/statement_classifier.rb, app/views/statements/index.json.jbuilder, spec/services/statement_classifier_spec.rb
We're not completely convinced by the design of this yet, but it adds some important functionality: a link to let you fix the verification status if someone got it wrong.
I've also created https://github.com/mysociety/verification-pages/issues/374 to represent an issue that @tmtmtmtm raised with adding this functionality.
Fixes #27
=> Add a "Verified?" column to show/let you correct the verification

app/javascript/components/verifiable.html
=> Simplify verification buttons and text

lib/tasks/load.rake, script/toolforge-cron.daily
This makes a couple of changes that should help make the cron job more robust.
Part of #390
=> Make cron job more robust

Gemfile, Gemfile.lock, config/initializers/exception_notification.rb
Fixes #446 
Shouldn't need any further configuration as I have setup the ENV variables on Toolforge.
=> [#446] Add exception_notification gem and configure

app/controllers/pages_controller.rb
=> [#462] Skip authentication for the Pages#index JSON

app/controllers/countries_controller.rb, app/views/countries/show.html.erb, config/routes.rb, spec/controllers/countries_controller_spec.rb
This loads the statements for all pages belonging to this country.
Fixes #475
=> Add "Load statements" button to country page

app/models/reconciliation.rb, app/services/load_statements.rb, spec/services/load_statements_spec.rb
=> [#443] Restore reconciliations

app/models/sparql_result.rb, app/services/concerns/sparql_query.rb, spec/models/sparql_result_spec.rb
Small changes required for #486
=> SparqlResult inherit from Hash

app/services/concerns/sparql_query.rb, app/services/retrieve_all_position_data.rb, lib/tasks/data_check.rake
Fixes #467 
Connects to #236 & #314 
Script output: https://gist.github.com/gbp/52eb5e5d3e7462d4792fb92ae3b3359a
This is over reporting at the moment (see UK 50th in the output) so we might want the checks to be expanded to ignore false positives but for now I think this gives us a good idea of what bad data we have created.
=> [#467] Add rake task to report bad data on Wikidata 

.rubocop_todo.yml, Gemfile, Gemfile.lock, app/controllers/frontend_controller.rb, app/controllers/statements_controller.rb, app/decorators/new_statement_decorator.rb, app/services/new_retrieve_position_data.rb, app/services/new_statement_classifier.rb, app/services/retrieve_term_data.rb, app/services/statement_classifier.rb, spec/decorators/new_statement_decorator_spec.rb, spec/services/new_retrieve_position_data_spec.rb, spec/services/new_statement_classifier_spec.rb, spec/services/statement_classifier_spec.rb, spec/support/classified_as_helpers.rb
Part of #472
~~Requires #473~~
Requires #488 
~~Currently requires local copy of the `membership_comparison` gem with the `remove-wikidata-module` branch checked out.~~
=> [#472] Integrate membership comparison gem

Gemfile.lock
Fixes #502
Included changes:
https://github.com/everypolitician/membership-comparison/pull/15
https://github.com/everypolitician/membership-comparison/pull/17
=> [#502] Update membership-comparison gem

Gemfile.lock, app/services/new_retrieve_position_data.rb, app/services/new_statement_classifier.rb, app/services/retrieve_all_position_data.rb, app/services/retrieve_term_data.rb
Fixes #504 
Requires https://github.com/everypolitician/membership-comparison/pull/21
=> [#504] Pass EOPT/SONT through to membership comparison gem

app/controllers/statements_controller.rb, app/models/page.rb, app/models/sparql_result.rb, app/services/retrieve_items.rb, app/services/statement_classifier.rb, app/views/statements/statistics.html.erb, lib/tasks/data_check.rake, spec/models/page_spec.rb, spec/models/sparql_result_spec.rb, spec/services/retrieve_items_spec.rb, spec/services/statement_classifier_spec.rb, spec/support/page_setup.rb
=> [#487] Handle merged positions

app/services/load_statements.rb, app/views/pages/show.html.erb, spec/services/load_statements_spec.rb
=> [#516] Statement loaded count

app/javascript/app.js
=> Update sort by label for the statement type

Gemfile.lock, app/lib/wiki_page_template_tag.rb, app/services/update_verification_page.rb
Requires https://github.com/everypolitician/mediawiki-page-replaceable_content/pull/9
Fixes #549
=> [#549] Retain wiki templates

app/javascript/components/actionable.js, app/views/statements/index.json.jbuilder
=> [#550] Use custom reference URLs when actioning

app/lib/wiki_page_template_tag.rb, spec/controllers/wikidata_page_controller_spec.rb, spec/lib/wiki_page_template_tag_spec.rb
=> [#547] Configure the new item description on Wikidata

lib/tasks/data_check.rake
Small change to stop the data check page form changing as often.
=> Data check improvements

app/assets/stylesheets/pages.scss, app/controllers/application_controller.rb, app/controllers/concerns/admin_authentication.rb, app/controllers/pages_controller.rb, app/helpers/application_helper.rb, app/javascript/components/reconcilable.js, app/models/page.rb, app/views/countries/index.html.erb, app/views/general/index.html.erb, app/views/layouts/_flash.html.erb, app/views/layouts/_header.html.erb, app/views/layouts/application.html.erb, app/views/pages/index.html.erb, app/views/pages/show.html.erb, app/views/statements/index.json.jbuilder, config/locales/en.yml
This improves the admin UI, primary the Pages#index which was hard to follow due to the reference/CSV source URLs columns.
=> General admin cleanup

Gemfile.lock, app/services/page_classifier.rb, app/services/retrieve_items.rb, app/services/retrieve_position_data.rb, app/services/statement_classifier.rb, spec/services/page_classifier_spec.rb, spec/services/retrieve_items_spec.rb, spec/services/retrieve_position_data_spec.rb
Requires https://github.com/everypolitician/membership-comparison/pull/25 and will need to remove the Gemfile `branch` when that PR is merged.
Requires #564 
Fixes #314
=> [#314] Show conflicts when person already has a P39 for the position held superclass

app/javascript/app.html, app/javascript/app.js, app/javascript/components/actionable.js, app/javascript/components/done.js, app/javascript/components/loading.js, app/javascript/components/manually_actionable.js, app/javascript/components/reconcilable.js, app/javascript/components/removed.js, app/javascript/components/reverted.js, app/javascript/components/statement.html, app/javascript/components/statement.js, app/javascript/components/unverifiable.js, app/javascript/components/verifiable.js, app/views/statements/index.json.jbuilder
Requires #593 
This isn't being used anymore so we don't need to pass this through to
the frontend components.
Checklist from #531
> - [x] clean up JSON and frontend
=> Remove country from statements JSON

app/services/generate_verification_page.rb, spec/services/generate_verification_page_spec.rb
Passing in an array of statements to the view is wrong as it calls the
on the PageClassifier class.
=> Fix Page generation

.babelrc, Gemfile, Gemfile.lock, bin/webpack, bin/webpack-dev-server, config/webpacker.yml, package.json, yarn.lock
Fixes #621 by upgrading Webpacker ruby gem/js package and other required packages.
=> [#621] Upgrade Webpacker

app/javascript/app.js, app/javascript/components/reconcilable.js, app/javascript/components/verifiable.html, app/javascript/components/verifiable.js, app/javascript/wikiapi.js, app/services/load_statements.rb
A few random fixes for issues discovered when documenting the frontend.
* fixes reference URL assignment 
* less likely to doesn't hang on JS errors
* correct column alias
=> Fixes to issues discovered when documenting the frontend

app/views/pages/_form.html.erb, app/views/pages/show.html.erb
Update the form attributes to the correct ones that exist.
This was meant to be done as part of #588
=> Fix new/edit page form and page show action

config/environments/production.rb
Quick change to make issues creating pages more visible.
Fixes: https://github.com/mysociety/verification-pages/issues/644
=> Show errors in production mode

lib/tasks/verification_page.rake, script/toolforge-cron
Instead of just generating the pages we actually want to update them.
Fixes: https://github.com/mysociety/verification-pages/issues/635
=> Switch crontab to use update:all rake task

app/javascript/app.html, app/javascript/components/statement.html, app/views/statements/index.json.jbuilder
This allows users to verify statements position start and end dates.
Fixes: https://github.com/mysociety/verification-pages/issues/649
=> Show dates on the frontend
