mysociety/verification-pages

config/webpack/environment.js
config/webpack/loaders/vue_template.js
package.json
yarn.lock

This allows CSS to be compiled into the tool's JS using an import EG:
`import template from './app.html?style=./app.css.scss'`

Enable Webpack CSS loader

---

app/javascript/app.css.scss
app/javascript/app.html
app/javascript/app.js

Fixes #77 by disabling “Type:” options if there are no statements with that type.
And probably fixes #75 for now, by at least showing the number of statements with each type. (#75 included a mockup of a much more "dashboardy" display of these totals, but maybe, for now, we can see how far this tiny change gets us, and revisit if people don’t find it obvious enough.)

Improvements to “Type:” dropdown filter

---

app/javascript/app.css.scss
app/javascript/app.html

Group the statement navigation controls together, away from the Type filter control, so it’s more obvious what "Next"/"Previous" relates to.
Also, tidy up the vertical padding.
Fixes #74.

Improve layout of main controls

---

app/services/update_verification_templates.rb

I'm not sure this code is actually being used, but I ran into a syntax error when trying to deploy the app to production. It seems that this error only show up in production because files are lazy-loaded in development, so this file isn't getting loaded.
Fixes #90

Fix syntax error in app/services/update_verification_templates.rb

---

app/controllers/verifications_controller.rb
app/models/statement.rb
app/services/create_verification.rb
spec/services/create_verification_spec.rb

This ensures that when a verifications is created for a statement, any duplicates of that statement also get verified.
I've also taken the opportunity to move the controller action's logic into a service object, rather than continue to bloat the controller action.
Fixes https://github.com/mysociety/verification-pages/issues/89

Mark duplicate statements as verified

---

app/javascript/packs/verification_tool.js
app/views/general/frontend.html.erb

It was weird that the page was still telling you to install the
JavaScript extension even after you'd done that successfully. This
change means it'll be removed if the JavaScript is loaded succesfully.
Fixes #70

After creating the Vue app, remove the "install our JavaScript" prompt

---

lib/tasks/verify_historic_duplicates.rake

This adds a small rake task that goes through all the original statements and then verifies any unverified duplicates.
Fixes #99

Add rake task to verify historic duplicates

---

.travis.yml
app/controllers/pages_controller.rb
app/models/country.rb
app/models/page.rb
app/views/pages/_form.html.erb
app/views/pages/index.html.erb
app/views/pages/show.html.erb
db/migrate/20180517094057_make_page_country_id_required.rb
db/schema.rb
spec/controllers/pages_controller_spec.rb
spec/factories/pages.rb

Now that we've added a `Country` model (https://github.com/mysociety/verification-pages/pull/95) and updated existing pages to have a `country_id` (https://github.com/mysociety/verification-pages/pull/101) we're finally ready to actually wire up the country model.
This change adds the Rails-level bits and pieces needed to properly associate pages with countries. I've also updated the pages views so that you can select a country from a dropdown when creating or editing a page, and see the country when viewing a page.
Fixes https://github.com/mysociety/verification-pages/issues/61

Wire up country model

---

Gemfile
Gemfile.lock
app/controllers/statements_controller.rb
app/lib/position_statistics.rb
app/lib/statements_statistics.rb
app/views/statements/statistics.html.erb
config/routes.rb
spec/lib/statements_statistics_spec.rb
spec/support/webmock.rb

This adds a new page which shows stats about the countries and positions that we already have statements for. This should allow us to figure out which pages need creating and what needs verifying.
Fixes https://github.com/mysociety/verification-pages/issues/104

Add statement statistics page

---

Gemfile
Gemfile.lock
README.md

This adds the `pry-rails` gem, which provides Rails integration for pry. This means that `rails console` will use pry instead of irb. It also means that `binding.pry` is available.
Fixes #109

Add pry-rails for better console and debugging

---

app/decorators/statement_decorator.rb
app/services/retrieve_position_data.rb
app/services/statement_classifier.rb
spec/services/statement_classifier_spec.rb

Prior to this commit, a statement that's been successfully actioned and
goes to "done" will move back to "actionable" if they're later merged
into someone else (which effectively deletes the original person we
reconciled and against, and redirects them to the person they were
merged into).
This commit changes the query we make to find current members of the
legislature to include previous item IDs the people might have had in
the past, and will match the person based on those item IDs as well as
the person's current item ID when looking them up.
This should fix a good proportion of the cases in #105, where people are
still in "actionable" although the have the right P39 already.

Handle people being merged into someone else after reconciliation

---

app/lib/position_statistics.rb
app/lib/statements_statistics.rb
app/views/statements/statistics.html.erb
spec/lib/statements_statistics_spec.rb

This means that you can go straight from the statistics page (showing
which pages still have things to do) to the page where you can deal with
them.
Fixes #115

Statistics page: link to any page(s) that exist for each position

---

Rakefile
lib/tasks/verification_page.rake

Code for custom rake tasks traditionally lives in `lib/tasks/` in a file with a `.rake` extension, to prevent the top-level `Rakefile` from getting too cluttered.

Move verification_page rake task into lib/tasks

---

spec/services/create_verification_spec.rb
spec/support/webmock.rb

It's not good to rely on a live API service (in this case id-mapping-store) in running tests; for example, it means you can't run the tests offline and it means they run slower. This pull request uses WebMock to stub the requests that the tests make to id-mapping-store and changes WebMock's configuration so that if any unstubbed HTTP requests are added in future, we'll get an error.
Fixes #112

Prevent live HTTP requests being made during tests

---

app/controllers/statements_controller.rb
app/models/statement.rb
app/services/statement_classifier.rb
db/migrate/20180606082434_add_actioned_at_to_statement.rb
db/schema.rb
spec/controllers/statements_controller_spec.rb
spec/services/statement_classifier_spec.rb

We are going to use this new actioned_at field to support a new
"reverted" state, which detects when we have enacted a suggestion (i.e.
taken it from "actionable" -> "done") but that position held statement was
later changed in Wikidata so it's no longer detected as "done".
This pull request, however, should just keep the current behaviour the same as
before, but relying on the actioned_at column of the statements table,
instead of keys with a 5 minute timeout in the Rails cache.

 Record the last time a Statement was actioned with a new actioned_at field

---

app/decorators/statement_decorator.rb
app/javascript/app.html
app/javascript/app.js
app/javascript/components/reverted.html
app/javascript/components/reverted.js
app/models/statement.rb
app/services/statement_classifier.rb
spec/services/statement_classifier_spec.rb

This is a new state to represent the fairly common situation that somone
has actioned a statement (that is: enacted it in Wikidata, moving the
statement to "done") but subsequenty it doesn't match what's in
Wikidata. This might be due to a Wikidata user reverting the change (or
a bug in our software) but in any case, we need to make sure we don't
encourage someone to try to action the satement again, which is what
would happen if it went back into the actionable state - hence this new
state instead, which doesn't prompt someone to make a change.
Note that to account for caching delays in detecting what's changed in
Wikidata, a statement still goes to "done" for 5 minutes after
actionining, regardless of whether it matches what we're getting back
from Wikidata queries - if they don't …

Add "reverted" for where actioned statements no longer match Wikidata

---

app/controllers/pages_controller.rb
app/views/pages/show.html.erb
config/routes.rb
spec/controllers/pages_controller_spec.rb

This adds a new button to an individual page which allows you to load the associated statements from the suggestions-store via the web UI.
Part of https://github.com/mysociety/verification-pages/issues/34

Add load statements button to pages

---

app/controllers/pages_controller.rb
app/services/concerns/wiki_client.rb
app/views/pages/show.html.erb
config/routes.rb
spec/controllers/pages_controller_spec.rb

This adds a new button to the `pages#show` route which creates or updates the associated verification page on Wikidata.
Part of #34

Add create/update page on Wikidata button to Pages

---

app/decorators/statement_decorator.rb
app/javascript/components/manually_actionable.html
app/javascript/components/manually_actionable.js
app/services/statement_classifier.rb
app/views/statements/index.json.jbuilder
spec/decorators/statement_decorator_spec.rb

The first commit in this pull requests doesn't change external behaviour, just how the manually_actionable state is calculated - changing it to be a determined by whether a list of "problems" is empty or not. The second commit updates the statement JSON and frontend JavaScript to render the reasons why a statement has ended up in manually_actionable.
Fixes #81

Show the reasons why a statement is in the 'manually_actionable' state

---

spec/controllers/pages_controller_spec.rb
spec/services/create_verification_spec.rb

This fixes a couple of cases where the stubbed URL should be based on an environment variable, and one instance where no requests seemed to be made to the stubbed URL in the tests, so we can save on some setup for the tests.

Fix minor problems with stubbed HTTP requests

---

README.md
app/controllers/concerns/admin_authentication.rb
app/controllers/countries_controller.rb
app/controllers/pages_controller.rb
app/javascript/packs/verification_tool.js
config/routes.rb

This adds basic auth to the countries and pages admin interfaces to prevent any unwanted changes.
At the moment I haven't written any tests for this, but I think it should hopefully be obvious enough if this isn't working.
Fixes #33 
Once this is merged we'll need to set `ADMIN_USERNAME` and `ADMIN_PASSWORD` on Toolforge in `~tools.verification-pages/verification-pages/environment_variables.sh` to enable it.

Add basic authentication for the admin pages

---

app/javascript/packs/verification_tool.js

We're using the wikibits importScript function to load the JavaScript
that creates the Vue app. This loads the JavaScript asynchronously.
The Vue app was only created once the window load event had fired,
however, so (when all the page assets were cached, in particular) the
load event might have been fired before our JavaScript runs - in that
case, nothing would happen.
There are two things we should change to fix this:
1. We only need to wait for the DOM to be ready, not all the page's
resources (e.g. images, CSS) as well, which is what waiting for the
'load' event did.
2. We should check if the DOM is already ready before waiting for that.
This commit makes those two changes. It seems that in the course of my
testing, however, the DOM is always loaded by the time our JavaScript
runs, …

Fix JavaScript not running because 'load' had already fired

---

app/controllers/pages_controller.rb
app/views/statements/statistics.html.erb
spec/controllers/pages_controller_spec.rb

This adds a button to the statistics page that allows you to create a missing page, prefilling some of the parameters for you.
Related to #139

Add link to create missing pages to statistics page

---

app/services/statement_classifier.rb
spec/services/statement_classifier_spec.rb

Now that we're dealing with external sources other than suggestions-store we have to handle the case where the external source is already reconciled to Wikidata but hasn't been verified.
This change checks that a statement has been both verified _and_ reconciled before considering it actionable.
Fixes #166 
The first commit changes another test for the actionable state because it wasn't creating a verification in the before block. My understanding is that statements *must* be verified before they are actionable, so I _think_ it's OK to make that change, but please say if I'm wrong!

Ensure statements are verified before they become actionable

---

app/decorators/statement_decorator.rb
spec/decorators/statement_decorator_spec.rb

There was a missing word in this error message.
Fixes https://github.com/mysociety/verification-pages/issues/187
(Note to reviewer: I don’t have a working dev environment, so haven’t checked the tests pass. I’m hoping/assuming that CI will take care of that, but if there's anything wrong here, feel free to fix it up or throw this PR away and fix separately.)

Fix missing word in "multiple statements" error

---

app/services/retrieve_position_data.rb
app/services/statement_classifier.rb
spec/services/retrieve_position_data_spec.rb
spec/services/statement_classifier_spec.rb

Fixes #186
Updates the `RetrievePositionData` SPARQL query to:
- Ignore positions statements if they started before the parliamentary term we are dealing with
- This means new positions statements will be created when statements are actioned.
We we're modifying historical position statements with incorrect data. Instead of creating a new statement.
The first two commits (975f5a0f92fe4b236023edfa5bf9bea98e667a2a...5b59ef4a390e24d2902680a10d3466b258cbf05e) have nothing to do with the new implementation but cover existing functionality in `RetrievePositionData` which wasn't being tested but I felt we needed to test before making changes.

[#186] Ignore historical position statements

---

app/controllers/reconciliations_controller.rb
app/decorators/statement_decorator.rb
app/javascript/components/reconcilable.html
app/javascript/components/reconcilable.js
app/models/reconciliation.rb
app/services/load_statements.rb
app/views/pages/show.html.erb
app/views/statements/index.json.jbuilder
db/migrate/20180627114341_change_csv_source_url_column_limit.rb
db/migrate/20180627135538_add_resource_type_to_reconciliations.rb
db/schema.rb
lib/tasks/add_resource_type_to_reconciliations.rake
spec/controllers/reconciliations_controller_spec.rb
spec/decorators/statement_decorator_spec.rb
spec/models/reconciliation_spec.rb
spec/services/load_statements_spec.rb
spec/services/statement_classifier_spec.rb

Fixes #151
Fixes #162
- Imports parliamentary group name/ item from source CSVs
- Output the parliamentary group in 'Statements to Action'
- Output the parliamentary group in the frontend Vue.js app
- Add functionality to the `Page#require_parliamentary_group?` boolean, if enabled:
- Statements can't be verified if we don't at least have a parliamentary group name
- Add 'Search for party' in the reconcile step if needed - EG if we only have a parliamentary group name and not its wikidata item ID in the source CSV
- Update the Reconciliation model to accept both `person` and `party` items
- and change the `after_commit` callback to update the statement correctly
- Creation of missing Wikidata parliamentary groups if they can't ben reconciled
- Automatically reconcile other statements with …

[#151] [#162] Handle statements with parliamentary groups

---

app/services/retrieve_position_data.rb

We want to return position statements even if it starts on the same day as the parliamentary term.

[#186] Fix statement loading

---

app/decorators/statement_decorator.rb
app/services/retrieve_position_data.rb
app/services/statement_classifier.rb
spec/services/statement_classifier_spec.rb

When multiple items have been `merged_then_deleted` into another item the same position will appear multiple times in the search results, once for each item that was deleted and merged into the master item.
This changes the SPARQL query to get `?merged_then_deleted` as a space-separated list, so each position should only appear in the query results once.
Fixes #153

Fix problem with multiple P39s being incorrectly detected

---

script/toolforge-backup-db

This script runs a simple MySQL dump and cleans up backups older than 7 days. It's intended to be run locally on the Toolforge grid via cron. Dump files can then by copied offsite from `db/` by a separate process.

Script for managing database backups

---

app/controllers/media_wiki_api_controller.rb

Running the Vue.js app locally we can't get past the 'Create person' reconciliation step as the API method requires a token.

Fix 'Create person' button for the API proxy

---

app/javascript/components/wikilink.html
app/javascript/components/wikilink.js
app/views/general/frontend.html.erb

Instead of linking to broken pages such as `https://verification.test/wiki/Q1` this uses the `WIKIDATA_SITE` environment variable to correctly link to the Wikidata site being used locally.

Link to Wikidata when running app locally

---

app/decorators/statement_decorator.rb
app/services/retrieve_position_data.rb
app/services/statement_classifier.rb
spec/decorators/statement_decorator_spec.rb
spec/services/statement_classifier_spec.rb

When multiple items have been `merged_then_deleted` into another item the same position will appear multiple times in the search results, once for each item that was deleted and merged into the master item.
This changes the SPARQL query to get `?merged_then_deleted` as a space-separated list, so each position should only appear in the query results once.
Fixes #153 
I've fixed the problem described in https://github.com/mysociety/verification-pages/issues/153#issuecomment-401862625 with a `fixup!` commit to make it clear what I've changed. I'll rebase and squash down that commit before merging this.

[Updated] Fix problem with multiple P39s being incorrectly detected

---

app/controllers/media_wiki_api_controller.rb
app/decorators/statement_decorator.rb
app/javascript/components/actionable.js
app/javascript/wikiapi.js
app/views/statements/index.json.jbuilder
spec/decorators/statement_decorator_spec.rb

Connects to: #175 - but not closes as we might want to add more references values too.
Makes it possible to add more than just a reference URL to statements. For now I have just added the date the reference was retrieved but it should be trivial now to add others
Better an more complete data on Wikidata.
This was hard to implement and I headed down the wrong rabbit hole a number of times. The important thing to note is API docs [1] mentions we can send through the previous reference hash to update the old reference. This is what I've now done but originally weren't doing this. I had thought we could just not send the values we didn't want updating (ala the original code and how qualifiers are handled), due to this being hard to test I spent a long time going the wrong direction. 
[1] …

[#175] Rework how references are added to statements

---

app/services/retrieve_position_data.rb

If a term has both a 'start time' and an 'inception', at the moment we
return two rows for each P39. Instead we should just pick one value.
This could be done with a relatively simple COALESCE if we always prefer
'inception', but it's useful to us to have term dates precise to the
day, so if 'start time' is of higher precision, we use that. Generally
we prefer 'inception', however, since that's the Wikidata consensus for
how the start of a term should be represented.
Fixes #239

Handle a term having both P580 (start time) and P571 (inception)

---

app/javascript/app.html
app/javascript/app.js
app/javascript/components/action_wrapper.html
app/javascript/components/action_wrapper.js
app/javascript/components/actionable.js
app/javascript/components/done.js
app/javascript/components/manually_actionable.js
app/javascript/components/reconcilable.js
app/javascript/components/reverted.js
app/javascript/components/unverifiable.js
app/javascript/components/verifiable.js

Fixes #221 
This PR changes how we are rendering the statements so everything can be seen at once. We've removed the pagination but filtering and actions do still work through a new action wrapper component. This was required to allow us to render different statement types at once and allowed us to have the submitting loading state affect only one statement at a time.

[#221] Render all statements in a table

---

app/javascript/app.html
app/javascript/app.js

Fixes #217.
Default sorting is still by last name but now we can also sort by party and district and then last name.
Re-rendering takes a moment to happen but the lag seems acceptable - we might need to revisit and implement a loading spinner later.

[#217] Allow sorting by party then last name, and district then last name

---

app/javascript/wikiapi.js

Fixes #169
Description languages need to match otherwise an "inconsitent-language" errors are raised.

[#169] Fix creating people when reconciling

---

lib/tasks/verification_page.rake
script/toolforge-cron.daily

Adds a rake task that iterates through the existing pages and re-generates the associated verification page on Wikidata. Also updates the crontab to include running that rake task.
Fixes #31

(Re-)generate verification pages daily

---

app/views/pages/index.html.erb

This makes it easier to actually view the page on Wikidata.
Fixes #261

Link to Wikidata page from list of pages

---

app/controllers/statements_controller.rb
app/decorators/statement_decorator.rb
app/javascript/app.css.scss
app/javascript/app.html
app/javascript/app.js
app/javascript/components/action_wrapper.html
app/javascript/components/action_wrapper.js
app/javascript/components/actionable.html
app/javascript/components/actionable.js
app/javascript/components/statement_change_summary.html
app/javascript/components/statement_change_summary.js
app/models/statement.rb
db/migrate/20180710103915_add_error_reported_and_reported_at_to_statements.rb
db/schema.rb
spec/controllers/statements_controller_spec.rb
spec/models/statement_spec.rb
spec/services/statement_classifier_spec.rb

Fixes #180 
Statements are automatically actioned on Wikidata when entering the `actionable` state after being verified and reconciled.
In effect most people, after clicking the verify or reconcile buttons, will see "short" submitting & updating messages followed by the done message.
If errors are raised then we show the error and a summary of the changes we attempted. We originally planned to move statements into the `manually_actionable` state if errors were raised. But on second thoughts felt that they might be transient errors which could be fixed by retrying, or the user might want to leave the statement in the `actionable` state and return at a future point. So the user is then given the option to 'Retry' or 'Report this statement' for someone …

[#180] Auto action statements

---

app/controllers/statements_controller.rb
app/decorators/statement_decorator.rb
app/javascript/components/actionable.js
app/javascript/components/manually_actionable.html
app/javascript/components/manually_actionable.js
app/models/statement.rb
app/views/statements/index.json.jbuilder
spec/controllers/statements_controller_spec.rb
spec/models/statement_spec.rb

Fixes #228.
Tweaks the `manually_actionable` template to include a button that lets you retry the statement update in Wikidata, once you think the previously reported error has been fixed.

[#228] Button to retry "fixed" `manually_actionable` statements

---

app/javascript/app.css.scss
app/javascript/components/reconcilable.html
app/javascript/components/reconcilable.js

Fixes #62.
User can override the Wikipedia against which reconciliations searches are performed. The setting defaults to `en.wikipedia.org`, but any country code can be entered – even if it’s not a real wikipedia. (Will need some error handling in `wikiapi.js` – #267 )
The user’s choice for any given "page" (eg: `User:Verification_pages_bot/verification/ca`) is stored in the browser’s LocalStorage, so it’ll persist between page reloads.

[#62] Configurable Wikipedia (language) search

---

app/decorators/statement_decorator.rb
app/services/statement_classifier.rb
spec/services/statement_classifier_spec.rb

When data comes from suggestions-store, it's important for us to check
whether it's correct, regardless of whether Wikidata already has that
information, so that our partner have a signal about whether individual
crowd-sourcers are performing well or not, and because we only allow
data through to their build which has been verified.
However, for external sources, where we're just using a verification
page to make sure the country is up-to-date, you usually would want to
completely skip over those cases since nothing needs to be done,
except possibly adding a reference URL.
Tony Bowden pointed out that we might want this to be a new state
("matches but not checked") so that people can go through those to add
the reference URLs, but will require updating the UI, and this is a good
first …

Skip verification of non-suggestions-store data that's already correct

---

app/controllers/pages_controller.rb
app/decorators/statement_decorator.rb
app/javascript/components/actionable.js
app/views/pages/_form.html.erb
app/views/pages/index.html.erb
app/views/pages/show.html.erb
app/views/statements/index.json.jbuilder
db/migrate/20180717102517_add_executive_position_to_pages.rb
db/schema.rb
spec/controllers/pages_controller_spec.rb
spec/services/statement_classifier_spec.rb

This adds an `executive_position` boolean column to the `pages` table. This is then checked in the javascript when we're building up a list of qualifiers and if it's `true` then we skip adding the electoral district and parliamentary group qualifiers, which doesn't make sense on executive positions. It also changes `StatementDecorator` to ignore districts and group qualifiers when matching executive positions to Wikidata.
Fixes #277 
Fixes https://github.com/mysociety/verification-pages/issues/285

Avoid adding incorrect qualifiers to executive positions

---

app/decorators/statement_decorator.rb
spec/decorators/statement_decorator_spec.rb
spec/services/statement_classifier_spec.rb

2a9a8743a34d75afa previously returned statements from the Wikidata Query
Service even if the position start date was up to roughly 4 weeks before
the start of the term (to accommodate the common situation where
politicians aren't formally inaugurated until some time after the
election, or the term has begun). However, if it was more than one day
before the term start date they were still being put into the
manually_actionable state. This commit changes the detection of this
problem so that the statement only goes into manually_actionable if the
position start_date is more than 31 days before the start of the term.
Fixes #297

Allow position start data up to a month before term start date

---

app/services/load_statements.rb
lib/tasks/restore_reconciliations.rake
spec/services/load_statements_spec.rb

If someone does a manual reconciliation on a Verification Page, then
that sets the person_item on that Statement. However, when the cron job
runs to update statements from the CSV source, the blank value from the
CSV file would overwrite person_item, losing the good work they'd done
and putting the statement into a confusing state. (We're also moving to
reconciling parliamentary groups and electoral districts, so the same
concern applies the reconciled values for them too.)
The first commit here changes LoadStatements.run so that it only
updates *_item attributes if there's actually a value for them in the CSV file.
The second commit adds a rake task to restore the items that were lost
by this bug.
Fixes #305

Stop periodically wiping out reconciled values, and add a script for restoring them

---

app/decorators/statement_decorator.rb
spec/decorators/statement_decorator_spec.rb
spec/services/statement_classifier_spec.rb

This adds a check to ignore any problems with `electoral_district_item` if that data wasn't provided in the source CSV. Previously it would have complained that the source didn't match Wikidata, but if none of the statements in the source have the district then it doesn't make sense to try and compare it.
Part of #238

Don't compare district information if it's not provided in the source

---

app/decorators/statement_decorator.rb
app/javascript/components/reconcilable.html
app/javascript/components/reconcilable.js
app/models/reconciliation.rb
spec/decorators/statement_decorator_spec.rb
spec/models/reconciliation_spec.rb

This is very similar to the changes in:
073d8b932680343567e63c5369c2581a72d7d14b
6a7806b3b2acd82a772f6042a9ca0d74eef67ab7
6ec170d9e2eb8e94d8a0b08284f09e8a3f1fbfaf
fe893cbe1cbb7c948c124c8084b188f75f26d8e9
a65b8bd3a35c0689a981d8e4d66d75a9db4a6d84
... which added support for reconciling parties, but this commit adds
support for reconciling districts.
(This doesn't add a "Create new item" button, so the districts have to
exist in Wikidata already, but we can add that later.)
Fixes #292

Basic support for reconciling districts

---

app/javascript/app.css.scss
app/javascript/app.html
app/javascript/app.js

This has the advantage of simplifying the interface and also adding a useful feature - you can now link directly to a statement.
Fixes #318 (and incidentally fixes #152)

Replace the transaction ID with a link to the statement

---

app/models/page.rb
spec/factories/pages.rb
spec/lib/statements_statistics_spec.rb

It turns out to be useful to be able to create multiple verification
pages, with different sources, for a single term of a particular
parliament. (e.g. you might have one from a scraper of the official
site, and another for a scraper of the Wikipedia page.)
This was being prevented, however, by the Page model having a uniqueness
constraint on 'position_held_item'. This commit changes the uniqueness
constraint on that model to be on 'title' instead. This makes sense
since the rest of the code already treats 'title' as a unique key for
the table (e.g. when the frontend Javascript fetches statements for a
page, it does it using the page title, not the position_held_item.)
Fixes #325

Make 'title', not 'position_held_item' the unique column on pages

---

app/javascript/wikiapi.js

If you supplied an unknown property ID to this function, the error you'd
get wouldn't be very helpful, because some completely different bit of
code would be using undefined instead of a property ID string.
The error if you provide an unknown server name could also be more
helpful.
This commit improves the error message in both of those cases.

Add better error-checking to getPropertyID

---

app/javascript/components/reverted.html

"This statement statement was actioned" should be "This statement was actioned".
Fixes #237

Fix typo of "statement statement"

---

app/controllers/pages_controller.rb
app/javascript/components/actionable.js
app/javascript/components/statement_change_summary.html
app/javascript/wikiapi.js
app/views/pages/_form.html.erb
app/views/pages/show.html.erb
app/views/statements/index.json.jbuilder
config/locales/en.yml
db/migrate/20180723140444_add_reference_url_title_and_language_to_page.rb
db/schema.rb
spec/controllers/pages_controller_spec.rb

This adds a `reference_url_title` and `reference_url_language` fields to the pages table, and then if set uses them for the `title` and `language of work or name` qualifiers on the reference URL.
Fixes #175

Additional reference URL qualifiers

---

app/javascript/app.css.scss
app/javascript/components/reconcilable.html
app/javascript/components/reconcilable.js

This also lays out the reconcilable component a bit more like a
standard search page.
Partial fix for #313.
Pair-programmed with Zarino Zappia (@zarino)

Allow custom search term during reconciliation

---

app/javascript/app.css.scss
app/javascript/components/reconcilable.html
app/javascript/components/reconcilable.js
app/javascript/components/verifiable.html
app/javascript/components/verifiable.js
package.json

Fixes #313. Work done while pairing with @mhl.
This completes the work in 71ac1a11d701c12c430d.

Rename person during reconcilation, rather than verification

---

app/javascript/app.css.scss
app/javascript/app.html

An effort to improve information density, as per #337.
In modern browsers, the table header will stick to the top of the
window as you scroll down the table. This required a slight change to
how we collapsed table borders (swapping `border-collapse: collapse`
for `border-spacing: 0`) because the `border-collapse` was resulting
in half-width (!!) borders when combined with `position: sticky`.

Move cell labels to top of table

---

app/decorators/statement_decorator.rb
spec/decorators/statement_decorator_spec.rb

If there are multiple P39 statements then _only_ show that error so the user can resolve that before moving on to other errors.
Fixes #338

When someone has multiple P39s don't show other errors

---

app/javascript/components/actionable.js
app/javascript/wikiapi.js
app/views/pages/_form.html.erb
app/views/pages/show.html.erb

This pull request disables the reference URL title and language that were added in #342. This is because it's not working correctly at the moment because of #364, but in order to fix it we need to supply a language code string for the title, but we only have the language as a `Q` value, and it's going to require more time than we have right now to resolve that.
Part of #364

Disable setting reference URL title and language

---

app/javascript/app.js
app/javascript/components/statement.html
app/javascript/components/statement.js

Now that there's a sticky header we need to scroll to a different point on the page when someone's navigating to a fragment.
Fixes #370

Fix scrolling to a fragment now there's a sticky table header

---

app/javascript/app.html
app/javascript/app.js

This adds an additional option to the "Sort by" dropdown to allow sorting by first name.
Fixes https://github.com/mysociety/verification-pages/issues/287
I've removed the `transaction_id` from the fields we were using for sorting as it didn't seem relevant, but I'm happy to add it back in if there's a reason we need it that I've missed!

Add option to sort by first name

---

app/javascript/components/actionable.html

This text didn't appear much any more, but it still provides a lot of
information that is only helpful to a very small minority of users, and
makes it look confusing and intimidating to the rest. It wasn't even very
helpful for developers, since it just showed how the qualifiers it would
like a P39 to have, and nothing about what was there already.
Fixes the first part of #384

Have a single, simple button for the 'actionable' state

---

app/javascript/app.html
app/javascript/app.js
app/javascript/components/sort_control.html
app/javascript/components/sort_control.js

This adds a "Type" option to the "Sort by" dropdown to allow you to sort statements by type. It also adds a "Sort" button, and the statements will only be re-sorted when that button is pressed.
Fixes #79
Fixes #372
Fixes #373

Replace filtering with sorting by statement type

---

app/controllers/frontend_controller.rb
app/controllers/reconciliations_controller.rb
app/javascript/app.js
app/javascript/components/actionable.js
app/javascript/components/done.js
app/javascript/components/manually_actionable.js
app/javascript/components/reconcilable.html
app/javascript/components/reconcilable.js
app/javascript/components/reverted.js
app/javascript/components/unverifiable.js
app/javascript/components/verifiable.js
app/models/reconciliation.rb
app/services/statement_classifier.rb
app/views/statements/index.json.jbuilder
db/migrate/20180728130458_add_update_type_to_reconciliations.rb
db/schema.rb
spec/controllers/reconciliations_controller_spec.rb
spec/models/reconciliation_spec.rb

Fixes #224 
Work done while pairing with @zarino.
Reconciling the a party will now also update other statements for the same party that are on the same page.
This all seems to be working but labelled as work in progress as the Ruby code needs tests updated/written. And the commit messages needs updating too. The frontend changes look good.
Switching to other features for now to make most use of pairing time.

[#224] Bulk party reconcilation

---

app/controllers/statements_controller.rb
app/views/statements/statistics.html.erb

If a country already exists in the database then show the full country name. Otherwise show the country code and a link to create that country.
Fixes #274

Show country name on statistics page

---

app/controllers/statements_controller.rb
app/lib/position_name_mapping.rb
app/views/statements/statistics.html.erb

This adds a PositionNameMapping class which looks up a list of items on
Wikidata and returns a mapping between the Qid and the label in English.
This is then used on the statistics page to show the full name of a
position, rather than just the ID.
Fixes #275 
Please complete the following **before** merging:

Show position labels on the statistics page

---

app/models/page.rb
db/migrate/20180809155552_change_page_reference_url_length.rb
db/schema.rb

We've run into problems where the reference URL is longer than we can fit into the `reference_url` column currently, so to avoid those problems increase the column's length to 2000, which is consistent with the length of `pages.csv_source_url`.
Fixes #361
Fixes #362

Increase length of pages.reference_url column

---

app/models/statement.rb
spec/factories/statements.rb
spec/models/statement_spec.rb
spec/services/create_verification_spec.rb

Otherwise we can't have the same person standing in the same position for
a different term.
Fixes: https://github.com/mysociety/verification-pages/issues/410

[#410] Duplicate statements must belong to the same page

---

README.md
app/javascript/app.html
app/javascript/app.js
app/javascript/components/statement.html
app/javascript/components/statement.js
app/javascript/components/verifiable.html
app/javascript/components/verifiable.js
app/models/verification.rb
app/services/create_verification.rb
db/migrate/20180817110527_add_reference_url_to_verifications.rb
db/schema.rb
spec/models/verification_spec.rb
spec/services/create_verification_spec.rb

This adds a `reference_url` column to the `verifications` and `statements` table, so that we can keep track of the URLs that were used to verify a statement over time, and also have the latest URL available on the statement.
It also updates the JavaScript UI so that you can specify a per-statement reference URL.
Fixes #46

Override reference url for individual statements

---

app/models/page.rb
app/models/statement.rb
app/views/pages/index.json.jbuilder
spec/models/page_spec.rb

We will need this from the politician-data build process in order to find
all the suggestions-store-backed verification pages set up for a
particular country.

Allow pages to viewed as JSON at /pages.json

---

.travis.yml
app/assets/javascripts/bootstrap.js
app/assets/javascripts/cable.js
app/assets/javascripts/verification.js
app/javascript/app.js
app/javascript/components/actionable.js
app/javascript/components/loading.js
app/javascript/components/reconcilable.js
app/javascript/components/statement.js
app/javascript/components/verifiable.js
app/javascript/components/wikilink.js
app/javascript/packs/verification_tool.js
app/javascript/wikiapi.js
app/views/general/frontend.html.erb
lib/tasks/lint.rake
lib/tasks/rubocop.rake
package.json
yarn.lock

Following on from this comment https://github.com/mysociety/verification-pages/pull/408#pullrequestreview-148857001 this pull request adds [standard JS](https://standardjs.com/) as the main linter for the project. This means it's a bit more opinionated than the ESLint version I did in #408, but I think that's probably a good thing for consistency.
Fixes #407

Add JavaScript linting with standard JS

---

app/controllers/statements_controller.rb
app/lib/statements_statistics.rb
app/views/statements/statistics.html.erb
spec/lib/statements_statistics_spec.rb

Statements without `position_item` were being rendered incorrectly.
Added a details table showing the transaction, district and role. These
are used to get the position item from politician-data repo.

Show invalid statements on statistic view

---

app/controllers/statements_controller.rb
app/lib/statements_statistics.rb
app/models/reconciliation.rb
app/views/statements/statistics.html.erb
spec/lib/statements_statistics_spec.rb
spec/models/reconciliation_spec.rb

Fixes: #418 
Not sure why I thought this was working for me yesterday. Possible due to a bad spec and worst still my analysts of missing claims was incorrect and gave me a wrong impression of the issue :(
Once I proved my initial thinking that all claims since a [certain date](https://github.com/mysociety/verification-pages/issues/418#issuecomment-416914938) were effected it was easier to track down.
Error introduced in c3eb88579310911850a54a5727af5ace3d4cd519.
Sigh.

[#418] Fix creation of equivalence claims

---

app/decorators/statement_decorator.rb
spec/services/statement_classifier_spec.rb

Paired programmed with @chrismytton

[#424] Fix statements being classifed as reverted if belonging to pages without terms

---

.travis.yml
Gemfile
Gemfile.lock
app/controllers/wikidata_page_controller.rb
app/lib/wiki_page_template_tag.rb
app/views/wikidata_page/wikidata_page_setup_error.html.erb
config/routes.rb
spec/controllers/wikidata_page_controller_spec.rb
spec/lib/wiki_page_template_tag_spec.rb

This adds a new route which accepts the title of a Wikidata page, then uses that to fetch the page and search for a template tag configuring the verification page. This config is used to create or update a page with a matching title, then we load in the statements for that page and generate a verification page with it. Finally it redirects back to the original verification page, now fully setup.
Fixes #330 
- No documentation yet. Have opened https://github.com/mysociety/verification-pages/issues/431 to track this.
- Need to bulk create all countries #402 
1. Check out this branch and get the server running
2. Add `WIKI_TEMPLATE_NAME=User:Chris_Mytton/sandbox/Template:Verification_page` to your `.env`
3. Change `WIKI_SITE` in `.env` to `www.wikidata.org`
4. Create a new page on …

On-wiki page creation using template parameters

---

app/decorators/statement_decorator.rb
app/models/statement.rb
app/services/statement_classifier.rb
spec/decorators/statement_decorator_spec.rb
spec/services/statement_classifier_spec.rb

Fixes #425
If a statement has been actioned and there are no P39 then something has
gone wrong. In this case we want to have the statement in the manually
actionable state we know to investigate it.

[#425] Detect when there are no matching P39

---

spec/factories/countries.rb
spec/factories/pages.rb
spec/factories/statements.rb

`Static attributes will be removed in FactoryBot 5.0. Please use dynamic
attributes instead`
Missed these when I merged #405

Fix FactoryBot deprecation warnings

---

app/decorators/statement_decorator.rb
spec/decorators/statement_decorator_spec.rb
spec/services/statement_classifier_spec.rb

Connects to #238 
Similar to #308 
This adds a check to ignore any problems with parliamentary group if that data wasn't provided in the source CSV. Previously it would have complained that the source didn't match Wikidata.

[#238] Only compare common fields

---

app/models/statement.rb
spec/models/statement_spec.rb

We recently added a required `reference_url` field to the `Verification` model, but forgot to update this bit of code to copy the reference URL over when creating duplicate verifications.
Fixes #419

Copy reference URL for duplicate verifications

---

README.md
app/lib/statements_statistics.rb
app/models/page.rb
app/services/update_statement_verification.rb
app/views/statements/statistics.html.erb
config/initializers/suggestions_store.rb
lib/suggestions_store.rb
lib/suggestions_store/request.rb
lib/tasks/add_csv_source_url_to_pages.rake
spec/lib/statements_statistics_spec.rb
spec/models/page_spec.rb
spec/models/statement_spec.rb
spec/models/verification_spec.rb
spec/services/statement_classifier_spec.rb
spec/services/update_statement_verification_spec.rb

Fixes #32 
Requires to https://github.com/mysociety/suggestions-store/pull/21
This extracts out requests to Suggestions Store into a common interface and adds the ability to use HTTP authentication.
Should consider rewriting existing specs to stub the new interface rather than the HTTP requests.

[#32] Use authenication for Suggestions Store requests

---

config/environments/production.rb

Fixes #446 
We missed the ActionMailer configuration when merging #457. I have tested this from the Rails console resulting in: https://groups.google.com/a/mysociety.org/forum/#!topic/cron-verification-pages/OO8-SA4FDj4

[#446] Configure ActionMailer to use Exim in production

---

app/lib/statements_statistics.rb
spec/lib/statements_statistics_spec.rb

The current statistics page is intended to be just about pages created from the suggestions-store data, but we were showing pages that were created from other sources.
This change adds an extra check to ensure we only display pages based on suggestions-store data on the statistics page.
Fixes #433

Only show suggestions-store pages on statistics page

---

app/decorators/statement_decorator.rb
app/javascript/components/removed.html
app/javascript/components/removed.js
app/javascript/components/statement.js
app/services/load_statements.rb
app/services/statement_classifier.rb
app/views/statements/index.json.jbuilder
db/migrate/20180911085714_add_removed_from_source_to_statements.rb
db/schema.rb
spec/decorators/statement_decorator_spec.rb
spec/factories/statements.rb
spec/services/load_statements_spec.rb
spec/services/statement_classifier_spec.rb

Fixes #316
If statement was in the `done` state and it is removed from the upstream source we now classify it as `removed`. And it is displayed as:
Should we also display this message for statements in other states: `reverted`, `manually_actionable`?

[#316] Classify statements as `removed` if they vanish from source

---

app/models/page.rb
app/models/page/transaction_id.rb
app/services/load_statements.rb
db/migrate/20180924100323_add_hash_epoch_to_pages.rb
db/migrate/20180924102808_increase_page_has_epoch.rb
db/schema.rb
spec/models/page/transaction_id_spec.rb
spec/services/load_statements_spec.rb

Fixes #380 
This adds the Page ID to the transaction ID hashes but keeps the original functionality for existing pages so statements aren't duplicated next time page CSV source is fetched.
Any future changes to these hash can be done by increment of the `Page#hash_epoch` value again.

[#380] Improve transaction ID hashes

---

.rubocop_todo.yml

It seems these Rubocop exclusions aren't needed anymore

Remove unneeded 'todo' Rubocop configuration

---

app/models/page/transaction_id.rb

To avoid clash with internal `Object#hash` Ruby methods.

Rename private method

---

app/controllers/pages_controller.rb
app/lib/statements_statistics.rb
app/views/pages/_form.html.erb
app/views/pages/show.html.erb
db/migrate/20181024075747_add_archived_to_pages.rb
db/schema.rb

This adds an `archived` column to the `pages` table. Archived pages won't appear on the statistics page, which means there will instead be a link to create a new page.
Fixes https://github.com/mysociety/verification-pages/issues/490

Allow pages to be archived

---

app/services/new_statement_classifier.rb

Identify issues with executive position pages (EG User:Verification_pages_bot/verification/ca/Mayor_of_Ottawa) which stop the membership comparison gem from detecting the exact match and classifying the statement as reverted.

Ignore districts for executive position

---

app/controllers/statements_controller.rb
app/decorators/new_statement_decorator.rb
app/models/statement.rb
db/migrate/20181025094234_add_classifier_version_to_statements.rb
db/schema.rb
spec/models/statement_spec.rb
spec/services/new_statement_classifier_spec.rb

Add classifier version to statements
This will store what version of the classifier was used to action a statement.
It will allow statements which have ended up in the reverted while using the old classifier to be actionable again if the new classifier is being used.

Record classifier version

---

app/controllers/frontend_controller.rb
spec/controllers/reconciliations_controller_spec.rb
spec/controllers/verifications_controller_spec.rb

Fixes #521 
Leaving the v1 classifier for now until we're ready to remove the code.

[#521] Switch to the new classifier by default

---

app/javascript/components/actionable.js

Fixes #499 
Within the wikiapi client can return promises which don't have the same
scope as outside so we need to use `that` instead of `this`.

[#499] Fix statement updating hanging after actioning

---

app/controllers/pages_controller.rb
app/controllers/statements_controller.rb
app/services/generate_verification_page.rb
app/services/new_statement_classifier.rb
app/services/statement_classifier.rb
spec/services/generate_verification_page_spec.rb

Connects to #521 
- Use new classifier when generating verification wiki pages
- Use new classifier query for the 'Find current positions from Wikidata' link on `admin/pages#show`
- Ensure the classifier version is saved when actioning as this might not be coming in via the params now - otherwise we could get prompted to action a statement more than once.

[#521] Switch to new classifier redux

---

app/models/statement.rb
app/services/load_statements.rb
spec/models/statement_spec.rb
spec/services/load_statements_spec.rb

[#536]  Prevent statements from going missing if updated in source CSV

---

app/services/load_statements.rb
spec/services/load_statements_spec.rb

Fixes #534
EveryPolitician CSV contain UUIDs in some matched columns so lets explicitly check for QIDs.

[#534] Matched CSV columns values could be not QIDs

---

app/controllers/pages_controller.rb
app/javascript/components/reconcilable.js
app/views/pages/_form.html.erb
app/views/pages/show.html.erb
app/views/statements/index.json.jbuilder
db/migrate/20181121143151_add_description_to_pages.rb
db/schema.rb

This adds a new column called `new_item_description_en` to the `pages` table. This column is intended to be the same as the `countries.description_en` column, but putting it on the page means we can make it configurable on-wiki.
Fixes https://github.com/mysociety/verification-pages/issues/530

Allow new person label to be configured on pages

---

app/models/page.rb
spec/models/page_spec.rb

Fixes #570
When country is nil we can't obviously access the `description_en` property.

[#570] Fix error being raise on `pages/new` action

---

app/javascript/components/actionable.js

We want this to be emitted as soon as possible to prevent users from
double clicking the `Submit to Wikidata` button.
Fixes #48

[#48] Emit loading event ASAP

---

Gemfile.lock
app/controllers/frontend_controller.rb
app/controllers/statements_controller.rb
app/decorators/statement_decorator.rb
app/services/generate_verification_page.rb
app/services/page_classifier.rb
app/services/retrieve_items.rb
app/services/statement_classifier.rb
app/views/statements/index.json.jbuilder
spec/controllers/reconciliations_controller_spec.rb
spec/controllers/verifications_controller_spec.rb
spec/services/generate_verification_page_spec.rb
spec/services/page_classifier_spec.rb
spec/services/statement_classifier_spec.rb

Fixes #304 
Classify statements as `manually actionable` if the person/ party/ district have been reconciled to a disambiguation page to prevent creating P39s. Users can edit the reconciliation to resolve the action the statement.
Commits ee1016c...441bb8f are basically a refactor to facilitate the help make the change required as small as possible.

[#304] Detect reconciliations to disambiguation page

---

app/models/sparql_result.rb
spec/models/sparql_result_spec.rb

Required to handle the subclasses for #314.
This improves SPARQL results by being able to handle arrays values. While to won't get arrays normally from the WDQS my intention is to map the results in the `RetrieveItems` service EG:
```
def run
run_query(query).each_with_object({}) do |result, memo|
result[:children] = [
{ item: result.delete(:child), label: result.delete(:child_label) },
]
memo[result[:item]][:children] += result[:children] if memo[result[:item]]
memo[result[:item]] ||= result
end
end
```

SPARQL results refactor

---

app/services/page_classifier.rb

Fixes #586 
This removes filtering of item data before passing it through to the `StatementClassifier`. The position data was being removed but is now required.
Without the position data the membership-comparison gem was ignoring the existing statements as the positions didn't match and caused the frontend to show the 'Submit to Wikidata' button for virtually all statements.

[#586] Fix incorrect states

---

app/controllers/pages_controller.rb
app/javascript/components/reconcilable.js
app/lib/wiki_page_template_tag.rb
app/models/page.rb
app/views/pages/_form.html.erb
app/views/pages/index.html.erb
app/views/pages/show.html.erb
app/views/statements/index.json.jbuilder
config/locales/en.yml
db/migrate/20190201152207_add_new_item_label_language_to_pages.rb
db/schema.rb
spec/controllers/wikidata_page_controller_spec.rb
spec/lib/wiki_page_template_tag_spec.rb
spec/models/page_spec.rb

Fixes #401 
Checklist from #531
> - [x] move the `label_lang` from the Country model to the Page model
> - [x] accept `label_lang` from wiki template tag
> - [x] double check the current `Country#description_en` values have been migrated to `Page#new_item_description_en` - see command on PR
We should run:
```sql
UPDATE pages AS p
INNER JOIN countries AS c ON c.id = p.country_id
SET
p.new_item_description_en = COALESCE(p.new_item_description_en, c.description_en),
p.new_item_label_language = COALESCE(p.new_item_label_language, c.label_lang)
```

[#401] Move label language over to Page class

---

app/controllers/pages_controller.rb
app/models/page.rb
app/views/pages/_form.html.erb
app/views/pages/index.html.erb
app/views/pages/show.html.erb
db/migrate/20190212141742_add_country_fields_to_pages.rb
db/schema.rb
spec/models/page_spec.rb

Connects to #458 & #459 making a start to derive Country from from position held and/or term items.
Checklist from #531
> - [x] add `Page#country_item` string column
> - [x] add `Page#country_name` string column
> - [x] add `Page#country_code` string column
> - [x] add `Page#country_item` to new page form
> - [x] add `Page#country_item` and `Page#country_name` to Page show and index views
> - [x] optional - setup automatic loading of `country_name`, like how `position_held_name`, `parliamentary_term_name` are retrieved from a SPARQL query - so we have countries names for new Verification Pages
> - [x] migrate existing `Country#wikidata_id` values have been migrated to `Page#country_item` - see command on PR #597 
> - [x] migrate existing `Country#name` values have been migrated to …

[#458] Add page country fields

---

app/models/page.rb
app/models/page/transaction_id.rb
app/views/pages/_form.html.erb
app/views/pages/show.html.erb
db/migrate/20190214152100_increase_page_has_epoch_3.rb
db/schema.rb
spec/controllers/pages_controller_spec.rb
spec/controllers/wikidata_page_controller_spec.rb
spec/factories/pages.rb
spec/models/page/transaction_id_spec.rb
spec/models/page_spec.rb

Connects to #458 & #459 use Page#country_item over Country#code for transaction IDs
Checklist from #531
> - [x] add Page validation to ensure if a page has `hash_epoch == 2` then an ISO country code item is valid - EG 2 or 3 characters
> - [x] change statement transaction ID generation hash from `{ country: country.code, ... }` to `{ country: page.country, ... }` - doesn't need a hash epoch increase as fields have been migrated to Page model
> - [x] increase statement transaction ID hash epoch - so we can differentiate Pages with ISO like country codes and those with Q-IDs
> - [x] add Page validation to ensure if a page has `hash_epoch == 3` then an Q-ID country item is valid

[#458] Update transaction ID generation

---

app/controllers/pages_controller.rb
app/javascript/components/reconcilable.html
app/javascript/components/reconcilable.js
app/javascript/wikiapi.js
app/lib/wiki_page_template_tag.rb
app/models/page.rb
app/views/pages/_form.html.erb
app/views/pages/index.html.erb
app/views/pages/show.html.erb
app/views/statements/index.json.jbuilder
config/locales/en.yml
db/migrate/20190306122639_rename_pages_label_language.rb
db/migrate/20190306125511_add_party_and_district_fields_to_pages.rb
db/schema.rb
spec/controllers/wikidata_page_controller_spec.rb
spec/lib/wiki_page_template_tag_spec.rb
spec/models/page_spec.rb

Fixes #588 will split out Wiki template sensible defaults into separate ticket/PR #624 
Requires #622 
Demo using the API proxy and test Wikidata instance.
Created:
- https://test.wikidata.org/wiki/Q197895
- https://test.wikidata.org/wiki/Q197896

[#588] Allow frontend to create parties and districts

---

app/services/retrieve_position_data.rb
app/services/retrieve_term_data.rb
spec/services/retrieve_position_data_spec.rb

This ensures when comparing dates in the membership-comparison gem we're
comparing dates with dates, instead of dates with strings.
Fixes #655

[#655] Parse dates from SPARQL queries

---

app/services/statement_classifier.rb

This was breaking the district comparison and classify statements as
exact matches when they weren't.
Fixes: https://github.com/mysociety/verification-pages/issues/636

Pass correct data to membership comparison gem

---

app/models/statement.rb

Check the parliamentary group and dates in order to allow multiple
statements for the same person with in the same term.
Fixes: https://github.com/mysociety/verification-pages/issues/646

Improve duplicate detection

---

app/services/retrieve_position_data.rb
app/services/retrieve_term_data.rb

SPARQL might sometimes return a invalid date, EG for the next_term_start
if there isn't a next term.
Invalid dates are set to nil.

Only parse dates which looks like a date
